/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 회원가입 */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이메일 인증 */
        post: operations["AuthController_verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/send-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 인증번호 발송 (회원가입 1단계) */
        post: operations["AuthController_sendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그인 */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 토큰 갱신 */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 로그아웃 */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 정보 조회 */
        get: operations["AuthController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 닉네임 변경 */
        patch: operations["AuthController_updateNickname"];
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 비밀번호 찾기 - 인증번호 발송 */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 비밀번호 찾기 - 인증번호 확인 */
        post: operations["AuthController_verifyPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 비밀번호 찾기 - 새 비밀번호 설정 */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 전체 주식 조회 */
        get: operations["StockController_findAll"];
        put?: never;
        /** 주식 추가 */
        post: operations["StockController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 주식 상세 조회 */
        get: operations["StockController_findOne"];
        /** 주식 수정 */
        put: operations["StockController_update"];
        post?: never;
        /** 주식 삭제 */
        delete: operations["StockController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yahoo/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 종목 현재가 조회 */
        get: operations["YahooController_getQuote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yahoo/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 종목 검색 */
        get: operations["YahooController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investment-profile/survey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 투자성향 설문 질문 조회 */
        get: operations["InvestmentProfileController_getSurveyQuestions"];
        put?: never;
        /** 투자성향 설문 제출 */
        post: operations["InvestmentProfileController_submitSurvey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investment-profile/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 투자성향 조회 */
        get: operations["InvestmentProfileController_getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 전체 용어 목록 조회 */
        get: operations["GlossaryController_getAllTerms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/glossary/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 카테고리 목록 조회 */
        get: operations["GlossaryController_getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/glossary/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 용어 검색 */
        get: operations["GlossaryController_searchTerms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/glossary/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 오늘의 용어 (랜덤) */
        get: operations["GlossaryController_getRandomTerm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/glossary/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 단일 용어 조회 */
        get: operations["GlossaryController_getTermById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/glossary/{id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 연관 용어 조회 */
        get: operations["GlossaryController_getRelatedTerms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 통합 뉴스 조회 (한국 + 해외) */
        get: operations["NewsController_getCombinedNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 뉴스 검색 (키워드로 제목/요약 검색) */
        get: operations["NewsController_searchNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 해외 시장 뉴스 조회 (Finnhub) - 무한스크롤 지원 */
        get: operations["NewsController_getMarketNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/market/korea": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 한국 시장 뉴스 조회 (네이버 금융) - 무한스크롤 지원 */
        get: operations["NewsController_getKoreanMarketNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/stock/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 해외 종목 뉴스 조회 (Finnhub) - 무한스크롤 지원 */
        get: operations["NewsController_getStockNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/stock/korea/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 한국 종목 뉴스 조회 (네이버 금융) - 무한스크롤 지원 */
        get: operations["NewsController_getKoreanStockNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 뉴스 카테고리 목록 */
        get: operations["NewsController_getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/users/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** [DEV] 이메일로 계정 삭제 */
        delete: operations["DevController_deleteUserByEmail"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/users/id/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** [DEV] ID로 계정 삭제 */
        delete: operations["DevController_deleteUserById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /**
             * @description 이메일
             * @example user@example.com
             */
            email: string;
            /**
             * @description 비밀번호 (최소 8자)
             * @example password123
             */
            password: string;
            /**
             * @description 닉네임 (최대 8자)
             * @example 홍길동
             */
            nickname: string;
        };
        ValidationErrorResponseDto: {
            /**
             * @description 에러 코드
             * @example STOCK_404
             */
            code: string;
            /**
             * @description 에러 메시지
             * @example 주식을 찾을 수 없습니다.
             */
            message: string;
            /**
             * @description HTTP 상태 코드
             * @example 404
             */
            statusCode: number;
            /**
             * @description 에러 발생 시간
             * @example 2026-01-26T12:00:00.000Z
             */
            timestamp: string;
            /**
             * @description 요청 경로
             * @example /stocks/1
             */
            path: string;
            /**
             * @description 유효성 검사 에러 목록
             * @example [
             *       {
             *         "field": "symbol",
             *         "constraints": {
             *           "isNotEmpty": "종목 코드는 필수입니다."
             *         }
             *       },
             *       {
             *         "field": "quantity",
             *         "constraints": {
             *           "min": "수량은 1 이상이어야 합니다."
             *         }
             *       }
             *     ]
             */
            details?: Record<string, never>;
        };
        ErrorResponseDto: {
            /**
             * @description 에러 코드
             * @example STOCK_404
             */
            code: string;
            /**
             * @description 에러 메시지
             * @example 주식을 찾을 수 없습니다.
             */
            message: string;
            /**
             * @description HTTP 상태 코드
             * @example 404
             */
            statusCode: number;
            /**
             * @description 에러 발생 시간
             * @example 2026-01-26T12:00:00.000Z
             */
            timestamp: string;
            /**
             * @description 요청 경로
             * @example /stocks/1
             */
            path: string;
            /**
             * @description 추가 에러 정보
             * @example {
             *       "field": "symbol",
             *       "reason": "필수 값입니다."
             *     }
             */
            details?: Record<string, never>;
        };
        VerifyEmailDto: {
            /**
             * @description 이메일
             * @example user@example.com
             */
            email: string;
            /**
             * @description 6자리 인증번호
             * @example 123456
             */
            code: string;
        };
        SendVerificationDto: {
            /**
             * @description 이메일
             * @example user@example.com
             */
            email: string;
        };
        LoginDto: {
            /**
             * @description 이메일
             * @example user@example.com
             */
            email: string;
            /**
             * @description 비밀번호
             * @example password123
             */
            password: string;
        };
        TokenResponseDto: {
            /**
             * @description 액세스 토큰
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /**
             * @description 리프레시 토큰
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refreshToken: string;
        };
        UserResponseDto: {
            /**
             * @description 유저 ID
             * @example 1
             */
            id: number;
            /**
             * @description 이메일
             * @example user@example.com
             */
            email: string;
            /**
             * @description 닉네임
             * @example 홍길동
             */
            nickname: string;
            /**
             * @description 이메일 인증 여부
             * @example true
             */
            isEmailVerified: boolean;
            /**
             * Format: date-time
             * @description 생성일
             * @example 2026-01-26T12:00:00.000Z
             */
            createdAt: string;
        };
        UpdateNicknameDto: {
            /**
             * @description 새 닉네임 (최대 8자)
             * @example 새닉네임
             */
            nickname: string;
        };
        ForgotPasswordDto: {
            /**
             * @description 가입된 이메일
             * @example user@example.com
             */
            email: string;
        };
        VerifyPasswordResetDto: {
            /**
             * @description 이메일
             * @example user@example.com
             */
            email: string;
            /**
             * @description 6자리 인증번호
             * @example 123456
             */
            code: string;
        };
        ResetPasswordDto: {
            /**
             * @description 이메일
             * @example user@example.com
             */
            email: string;
            /**
             * @description 6자리 인증번호
             * @example 123456
             */
            code: string;
            /**
             * @description 새 비밀번호 (최소 8자)
             * @example newPassword123
             */
            newPassword: string;
        };
        CreateStockDto: {
            /**
             * @description 종목 코드
             * @example 005930.KS
             */
            symbol: string;
            /**
             * @description 종목명
             * @example 삼성전자
             */
            name: string;
            /**
             * @example domestic
             * @enum {string}
             */
            category: "domestic" | "overseas";
            /**
             * @description 보유 수량
             * @example 10
             */
            quantity: number;
            /**
             * @description 평균 매수가
             * @example 75000
             */
            avgPrice: number;
            /**
             * @description 통화
             * @example KRW
             */
            currency: string;
        };
        StockResponseDto: {
            id: number;
            symbol: string;
            name: string;
            /** @enum {string} */
            category: "domestic" | "overseas";
            quantity: number;
            avgPrice: number;
            currency: string;
            /** @description Yahoo에서 가져온 현재가 */
            currentPrice?: number;
            /** @description 수익률 % */
            profitPercent?: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateStockDto: {
            /**
             * @description 종목 코드
             * @example 005930.KS
             */
            symbol?: string;
            /**
             * @description 종목명
             * @example 삼성전자
             */
            name?: string;
            /**
             * @example domestic
             * @enum {string}
             */
            category?: "domestic" | "overseas";
            /**
             * @description 보유 수량
             * @example 10
             */
            quantity?: number;
            /**
             * @description 평균 매수가
             * @example 75000
             */
            avgPrice?: number;
            /**
             * @description 통화
             * @example KRW
             */
            currency?: string;
        };
        YahooQuoteDto: {
            /**
             * @description 종목 심볼
             * @example 005930.KS
             */
            symbol: string;
            /**
             * @description 짧은 종목명
             * @example 삼성전자
             */
            shortName: string;
            /**
             * @description 긴 종목명
             * @example Samsung Electronics Co., Ltd.
             */
            longName: string;
            /**
             * @description 통화
             * @example KRW
             */
            currency: string;
            /**
             * @description 현재가
             * @example 75000
             */
            regularMarketPrice: number;
            /**
             * @description 변동액
             * @example 1500
             */
            regularMarketChange: number;
            /**
             * @description 변동률 (%)
             * @example 2.04
             */
            regularMarketChangePercent: number;
            /**
             * @description 전일 종가
             * @example 73500
             */
            regularMarketPreviousClose: number;
            /**
             * @description 52주 최고가
             * @example 85000
             */
            fiftyTwoWeekHigh: number;
            /**
             * @description 52주 최저가
             * @example 55000
             */
            fiftyTwoWeekLow: number;
        };
        YahooSearchResultDto: {
            /**
             * @description 종목 심볼
             * @example 005930.KS
             */
            symbol: string;
            /**
             * @description 짧은 종목명
             * @example 삼성전자
             */
            shortname: string;
            /**
             * @description 긴 종목명
             * @example Samsung Electronics Co., Ltd.
             */
            longname: string;
            /**
             * @description 거래소 코드
             * @example KSC
             */
            exchange: string;
            /**
             * @description 거래소명
             * @example Korea Stock Exchange
             */
            exchDisp: string;
            /**
             * @description 섹터
             * @example Technology
             */
            sector?: string;
            /**
             * @description 산업
             * @example Consumer Electronics
             */
            industry?: string;
        };
        SurveyOptionDto: {
            /** @example 1 */
            value: Record<string, never>;
            /** @example 19세 이하 */
            label: string;
            /** @example 20 */
            score: number;
            /** @example 가장 안전한 투자 상품들 */
            description?: string;
        };
        SurveyQuestionDto: {
            /** @example 1 */
            id: number;
            /** @example 고객님의 연령대는 어떻게 되십니까? */
            question: string;
            options: components["schemas"]["SurveyOptionDto"][];
        };
        SurveyQuestionsResponseDto: {
            /** @description 설문 질문 목록 */
            questions: components["schemas"]["SurveyQuestionDto"][];
        };
        SubmitSurveyDto: {
            /**
             * @description 연령대 (1: 19세 이하, 2: 20~40세, 3: 41~50세, 4: 51~60세, 5: 61세 이상)
             * @example 2
             */
            q1Age: number;
            /**
             * @description 투자 경험 (1: 예적금, 2: 채권형, 3: 혼합형, 4: 주식형, 5: 파생상품)
             * @example 4
             */
            q2Experience: number;
            /**
             * @description 지식 수준 (1: 경험없음, 2: 주식채권 구분, 3: 대부분 상품, 4: 모든 상품)
             * @example 3
             */
            q3Knowledge: number;
            /**
             * @description 손실 감내 (1: 원금보전 필수, 2: 최소 손실, 3: 일부 손실, 4: 높은 위험 OK)
             * @example 3
             */
            q4RiskTolerance: number;
            /**
             * @description 투자 기간 (1: 6개월 미만, 2: 6개월~1년, 3: 1~2년, 4: 2~3년, 5: 3년 이상)
             * @example 5
             */
            q5Period: number;
            /**
             * @description 자산 대비 비중 (1: 10% 이하, 2: 10~20%, 3: 20~30%, 4: 30~40%, 5: 40% 초과)
             * @example 2
             */
            q6AssetRatio: number;
            /**
             * @description 수입원 (1: 안정/증가 예상, 2: 감소/불안정, 3: 연금)
             * @example 1
             */
            q7Income: number;
            /**
             * @description 시장 선호도
             * @example balanced
             * @enum {string}
             */
            marketPreference: "domestic_only" | "domestic_preferred" | "balanced" | "us_preferred" | "us_only";
        };
        RecommendedProductDto: {
            /** @example 국내 주식형 ETF */
            category: string;
            /**
             * @example [
             *       "KODEX 200",
             *       "TIGER 반도체"
             *     ]
             */
            examples: string[];
            /**
             * @description 추천 비중 (%)
             * @example 30
             */
            ratio: number;
        };
        InvestmentProfileResponseDto: {
            /** @example 75 */
            totalScore: number;
            /**
             * @example 2
             * @enum {number}
             */
            grade: 1 | 2 | 3 | 4 | 5;
            /** @example 적극투자형 */
            gradeName: string;
            /** @example 투자원금의 보전보다는 위험을 감내하더라도 높은 수준의 투자수익을 추구합니다. */
            gradeDescription: string;
            /**
             * @example us_preferred
             * @enum {string}
             */
            marketPreference: "domestic_only" | "domestic_preferred" | "balanced" | "us_preferred" | "us_only";
            /** @example 미국 선호 */
            marketPreferenceName: string;
            recommendedProducts: components["schemas"]["RecommendedProductDto"][];
        };
        GlossaryTermDto: {
            /** @example 1 */
            id: number;
            /** @example PER */
            term: string;
            /** @example Price Earning Ratio */
            termEn?: string;
            /** @example 주가수익비율. 주가가 주당순이익(EPS)의 몇 배인지 나타내는 지표 */
            definition: string;
            /** @example PER 10 = 현재 주가가 1년 순이익의 10배 */
            example?: string;
            /**
             * @example analysis
             * @enum {string}
             */
            category: "beginner" | "trading" | "analysis" | "news" | "slang";
            /** @example 분석 지표 */
            categoryName: string;
            /**
             * @example [
             *       "PBR",
             *       "EPS"
             *     ]
             */
            relatedTerms?: string[];
        };
        GlossaryListResponseDto: {
            terms: components["schemas"]["GlossaryTermDto"][];
            /** @example 50 */
            total: number;
        };
        GlossaryCategoryDto: {
            /**
             * @example analysis
             * @enum {string}
             */
            category: "beginner" | "trading" | "analysis" | "news" | "slang";
            /** @example 분석 지표 */
            name: string;
            /** @example 15 */
            count: number;
        };
        GlossaryCategoriesResponseDto: {
            categories: components["schemas"]["GlossaryCategoryDto"][];
        };
        GlossarySearchResponseDto: {
            results: components["schemas"]["GlossaryTermDto"][];
            /** @example 매수 */
            query: string;
            /** @example 5 */
            count: number;
        };
        NewsItemDto: {
            /** @description 뉴스 ID */
            id: string;
            /** @description 뉴스 제목 */
            title: string;
            /** @description 뉴스 요약 */
            summary?: string;
            /** @description 뉴스 원문 URL */
            url: string;
            /** @description 뉴스 소스 (언론사) */
            source: string;
            /** @description 이미지 URL */
            imageUrl?: string;
            /** @description 발행 시간 (ISO 8601) */
            publishedAt: string;
            /** @description 관련 종목 심볼 */
            relatedSymbols?: string[];
            /**
             * @description 뉴스 출처
             * @enum {string}
             */
            newsSource: "finnhub" | "naver";
            /**
             * @description 카테고리
             * @enum {string}
             */
            category?: "general" | "stock" | "economy" | "world";
        };
        NewsListResponseDto: {
            /** @description 뉴스 목록 */
            news: components["schemas"]["NewsItemDto"][];
            /** @description 현재 페이지 개수 */
            total: number;
            /** @description 현재 페이지 */
            page?: number;
            /** @description 다음 페이지 존재 여부 */
            hasMore?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description 회원가입 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효성 검사 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseDto"];
                };
            };
            /** @description 이미 존재하는 이메일 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailDto"];
            };
        };
        responses: {
            /** @description 이메일 인증 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효하지 않은 인증번호 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_sendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendVerificationDto"];
            };
        };
        responses: {
            /** @description 인증번호 발송 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 이미 존재하는 이메일 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 토큰 갱신 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그아웃 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_updateNickname: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNicknameDto"];
            };
        };
        responses: {
            /** @description 닉네임 변경 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효성 검사 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseDto"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            /** @description 인증번호 발송 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 가입되지 않은 이메일 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_verifyPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyPasswordResetDto"];
            };
        };
        responses: {
            /** @description 인증 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효하지 않은 인증번호 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            /** @description 비밀번호 변경 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증되지 않음 또는 유효하지 않은 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    StockController_findAll: {
        parameters: {
            query?: {
                category?: "domestic" | "overseas";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockResponseDto"][];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    StockController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStockDto"];
            };
        };
        responses: {
            /** @description 주식 추가 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockResponseDto"];
                };
            };
            /** @description 유효성 검사 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseDto"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    StockController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockResponseDto"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description 주식을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    StockController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStockDto"];
            };
        };
        responses: {
            /** @description 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockResponseDto"];
                };
            };
            /** @description 유효성 검사 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseDto"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description 주식을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    StockController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description 주식을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    YahooController_getQuote: {
        parameters: {
            query: {
                /** @description 종목 심볼 */
                symbol: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YahooQuoteDto"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    YahooController_search: {
        parameters: {
            query: {
                /** @description 검색어 */
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 검색 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YahooSearchResultDto"][];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description 서버 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    InvestmentProfileController_getSurveyQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 설문 질문 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyQuestionsResponseDto"];
                };
            };
        };
    };
    InvestmentProfileController_submitSurvey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitSurveyDto"];
            };
        };
        responses: {
            /** @description 설문 제출 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentProfileResponseDto"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    InvestmentProfileController_getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 투자성향 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentProfileResponseDto"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description 투자성향 미등록 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    GlossaryController_getAllTerms: {
        parameters: {
            query?: {
                /** @description 카테고리 필터 */
                category?: "beginner" | "trading" | "analysis" | "news" | "slang";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 용어 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryListResponseDto"];
                };
            };
        };
    };
    GlossaryController_getCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 카테고리 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryCategoriesResponseDto"];
                };
            };
        };
    };
    GlossaryController_searchTerms: {
        parameters: {
            query: {
                /** @description 검색어 */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 검색 결과 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossarySearchResponseDto"];
                };
            };
        };
    };
    GlossaryController_getRandomTerm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 랜덤 용어 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryTermDto"];
                };
            };
        };
    };
    GlossaryController_getTermById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 용어 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryTermDto"];
                };
            };
            /** @description 용어 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    GlossaryController_getRelatedTerms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 연관 용어 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryTermDto"][];
                };
            };
        };
    };
    NewsController_getCombinedNews: {
        parameters: {
            query?: {
                /** @description 페이지 크기 */
                limit?: number;
                /** @description 페이지 번호 (1부터 시작) */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 뉴스 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsListResponseDto"];
                };
            };
        };
    };
    NewsController_searchNews: {
        parameters: {
            query: {
                /** @description 페이지 크기 */
                limit?: number;
                /** @description 페이지 번호 (1부터 시작) */
                page?: number;
                /** @description 검색 키워드 */
                keyword: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 검색 결과 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsListResponseDto"];
                };
            };
        };
    };
    NewsController_getMarketNews: {
        parameters: {
            query?: {
                /** @description 페이지 크기 */
                limit?: number;
                /** @description 페이지 번호 (1부터 시작) */
                page?: number;
                /** @description 카테고리 */
                category?: "general" | "stock" | "economy" | "world";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 뉴스 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsListResponseDto"];
                };
            };
        };
    };
    NewsController_getKoreanMarketNews: {
        parameters: {
            query?: {
                /** @description 페이지 크기 */
                limit?: number;
                /** @description 페이지 번호 (1부터 시작) */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 뉴스 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsListResponseDto"];
                };
            };
        };
    };
    NewsController_getStockNews: {
        parameters: {
            query?: {
                /** @description 페이지 크기 */
                limit?: number;
                /** @description 페이지 번호 (1부터 시작) */
                page?: number;
            };
            header?: never;
            path: {
                /** @description 종목 심볼 (예: AAPL, MSFT) */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 뉴스 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsListResponseDto"];
                };
            };
        };
    };
    NewsController_getKoreanStockNews: {
        parameters: {
            query?: {
                /** @description 페이지 크기 */
                limit?: number;
                /** @description 페이지 번호 (1부터 시작) */
                page?: number;
            };
            header?: never;
            path: {
                /** @description 종목 코드 (예: 005930, 035720) */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 뉴스 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsListResponseDto"];
                };
            };
        };
    };
    NewsController_getCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 카테고리 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DevController_deleteUserByEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 삭제할 계정 이메일 */
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 계정 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DevController_deleteUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 삭제할 계정 ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 계정 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
